config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions:'users/sessions' }
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :destroy, :update]

  root 'homes#top'
  get 'home/about', to: 'homes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, length: { maximum: 200 }
  validates :title, presence: true
  validates :body, length: { maximum: 200 }
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
  end 
    
  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to users_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def create
    @books = Book.all
    @book = Book.new(book_params) #書き方をテキストで確認
    @book.user_id = current_user.id 
    if @book.save
      flash[:notice] = 'You have creatad book successfully.'
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def index
  end
  
end

app/controllers/users/application_controller.rb
Class Users::ApplicationController  < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  

  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def index
    @Users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end    
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb


<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <%= form_for @book do |f| %>
          <% if @book.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= @book.errors.count %> error prohibited this obj from being saved:
              </h2>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div>
            <%= f.label :title, "Title" %><br>
            <%= f.text_field :title, class: "form"  %>
          </div>
          <div>
            <%= f.label :body, "Opinion" %><br>
            <%= f.text_area :body, class: "form" %>
          </div>
          <div>
            <%= f.submit "Update Book", class: "btn" %>
          </div>
        <% end %>
        <%= link_to  "Show", book_path(@book.id) %>
        <%= link_to  "Back", books_path %>
      </div>
    </div>
  </div>
</body>

app/views/books/index.html.erb
<body>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render '/users/list', book: @book %>

    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>      
      </table>
    </div>

  </div>
</div>
</body>

app/views/books/show.html.erb

<%= render 'users/list', book: @new_book, current_user: @book.user %>

<div class="col-xs-9">
  <h2>Book detail</h2>
      <table class="table">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user_id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= @book.title %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @book.user == current_user %>
                <td>
                  <%= link_to "Edit", edit_book_path(@book.id) %>
                </td>
                <td>
                  <%= link_to "Destroy", "/books/#{@book.id}", method: :delete %>
                </td>
              <% end %>
            </tr>
        </tbody>      
      </table>
</div>

app/views/homes/index.html.erb
<div class='body'>
  <div class='container'>
    <div class="row">
      <div class='top-message col-md-offset-3 col-md-6'>
      
        <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
            <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
            <p>you can share and exchange  your opinions , inpressions , and emotions</p>
            <p> about various books!</p>
                
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class='body'>
  <div class='container'>
    <div class="row">
      <div class='top-message col-md-offset-3 col-md-6'>
      
        <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
            <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
            <p>you can share and exchange  your opinions , inpressions , and emotions</p>
            <p> about various books!</p>

        <div class="btn-wrapper">
          <div class="row">
            <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
          </div>
          <div class="row">
            <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
          </div>

        </div>                  
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="top-title">
          <nav class='nav navbar-nav navbar-left' >
            <span>Bookers</span>
          </nav>
        </div>
        <div class="navigate">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-edit sign_up" %></li>
                <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-edit users" %></li>
                <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-edit books" %></li>
                <li><%= link_to "logout", destroy_user_session_path, class: "glyphicon glyphicon-edit logout", method: :delete %></li>
              <% else %>
                <li><%= link_to "Home", root_path, class: "glyphicon glyphicon-home home" %></li>
                <li><%= link_to "About", home_about_path, class: "glyphicon glyphicon-link about" %></li>
                <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
                <li><%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li> 
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <body>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>

    </body>
    
    <footer>
      <div class='container'>
        <div class='row'>
          <div class='col-xs-3 col-xs-offset-9'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>

app/views/users/_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
      <div class="profile_img">
        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      </div>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <%= link_to edit_user_path(current_user) do %>
        <div class="wrench">
          <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        </div>
      <% end %>
      <h2>New book</h2> 
      <%= form_for(book) do |f| %>
        <div class="form">
          <%= f.label :name, "Title" %><br>
          <%= f.text_field :title, class: "form" %>
        </div>
        <div class="form">
          <%= f.label :body, "Opinion" %><br>
          <%= f.text_area :body, class: "form" %>
        </div>
        <div class="form">
          <%= f.submit 'Create Book', class: "btn" %>
        </div>
      <% end %>
    </div>

app/views/users/edit.html.erb
<body>
  <div class="container">
    <h2>User info</h2>
      <%= form_for @user do |f| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= @user.errors.count %> errors prohibited this obj from being saved:
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= f.label :name, "Name" %><br>
          <%= f.text_field :name %>
        </div>
        <div>
          <%= f.label :profile_image, "image" %>
          <%= f.attachment_field :profile_image, placeholder: "イメージ画像" %>
        </div>
        <div>
          <%= f.label :introduction, "Introduction" %><br>
          <%= f.text_area :introduction %>
        </div>
        <div>
          <%= f.submit %>
        </div>
      <% end %>
  </div>
</body>

app/views/users/index.html.erb
<body>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'users/list', book: @book%>

    <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @Users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>      
      </table>
    </div>

  </div>
</div>
</body>

app/views/users/show.html.erb

<%= render 'users/list', book: @book, current_user: @user %>

<div class="col-xs-9">
  <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>      
      </table>
</div>